### ISSUE TITLE
Documentation Issues

### ISSUE THREAD

**Issue by jcyannotty** [danOSU/Taweret#20]
Some minor things I noticed when trying to run "sh run_to_rebuild_tawret_rst.sh" - these could be Taweret issues OR it could be just be me:
1. If the user has jinja2 version 3.1 or higher, then they will get an error with sphinx. This is a jinja2 issue and was solved by downgrading my version to 3.0.3. We could specify this in the requirements file.

2. We may need to also include the sphinx related libraries in the requirement txt file. I had to install each one manually, which isn't a problem, but could be made easier on the user by automatically installing.

3. I received the error "Taweret/doces/source/contents.rst not found." - Should I have a contents.rst file? I rebased last night so everything should be up to date.

4. I am not using conda to edit the documentation. It might be good to include the pip commands in the documentation in addition to conda (?)

**Comment by danOSU** [comment]
1 & 2. Let’s modify the environment.yml file and the requirement.txt files with what is needed. Would you be able to do it and make a pull request? @jcyannotty

**Comment by danOSU** [comment]
3. Do you have more details about this error message? I don’t see that file either in the source directory. Where in the sphinx scripts does it look for contents.rst?

**Comment by jcyannotty** [comment]
This seems like a version issue.
https://github.com/readthedocs/readthedocs.org/issues/2569

Add code below to the conf.py file
master_doc = 'index.rst'

https://stackoverflow.com/questions/56336234/build-fail-sphinx-error-contents-rst-not-found
