### ISSUE TITLE
weird zero rows in the output of both data and sigma. Probably coming from TrueModel evaluation return structure inside Data class. 

### ISSUE THREAD

**Issue by danOSU** [danOSU/Taweret#42]
https://github.com/danOSU/Taweret/blob/02897a27264ca5948a0a2098af76f600c67ef438/Taweret/models/samba_models.py#L474C5-L474C5
![Screenshot 2023-08-14 at 11 28 49 AM](https://github.com/danOSU/Taweret/assets/38963118/03fdecc5-bcb3-450d-a110-7d60d4214342)

**Comment by asemposki** [comment]
Fixed. Was returning the empty std_dev accidentally, hence the zeros (since it uses the TrueModel function).
